# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-03 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_posts', '0003_auto_20200924_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_posts',
            name='likes',
            field=models.ManyToManyField(related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
