# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_posts', '0004_user_posts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_posts',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
