# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20201008_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='userprofile',
        ),
    ]
