# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_order_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='author',
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order'),
        ),
    ]
